In [ ]:
# Define a dictionary containing  data 
cities = {'City':["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]}

In [ ]:
import pandas as pd

# Convert the dictionary into DataFrame 
df = pd.DataFrame(cities) 
    
# Observe the result 
df

                            City
0              Mont Saint Michel
1                        St Malo
2                         Bayeux
3                       Le Havre
4                          Rouen
5                          Paris
6                         Amiens
7                          Lille
8                     Strasbourg
9   Chateau du Haut Koenigsbourg
10                        Colmar
11                     Eguisheim
12                      Besancon
13                         Dijon
14                        Annecy
15                      Grenoble
16                          Lyon
17              Gorges du Verdon
18            Bormes les Mimosas
19                        Cassis
20                     Marseille
21               Aix en Provence
22                       Avignon
23                          Uzes
24                         Nimes
25                 Aigues Mortes
26      Saintes Maries de la mer
27                     Collioure
28                   Carcassonne
29                        Ariege
30                      Toulouse
31                     Montauban
32                      Biarritz
33                       Bayonne
34                   La Rochelle

In [ ]:
import requests
import urllib.parse

df2 = pd.DataFrame()

for city in (df['City']):

  rep = requests.get("https://nominatim.openstreetmap.org/search?q=" + city + "&limit=1&format=json")
  df2 = df2.append(rep.json(), ignore_index=True)
  df2 = df2[["place_id","lat", "lon"]]
  df2.insert(0, 'City', df['City'])

<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)
<ipython-input-7-29be794ce5a2>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(rep.json(), ignore_index=True)

In [ ]:
df2

,City,place_id,lat,lon
0,Mont Saint Michel,156604780,48.6359541,-1.511459954959514
1,St Malo,298187446,48.649518,-2.0260409
2,Bayeux,298563984,49.2764624,-0.7024738
3,Le Havre,297969319,49.4938975,0.1079732
4,Rouen,297988461,49.4404591,1.0939658
5,Paris,297919168,48.8534951,2.3483915
6,Amiens,297990795,49.8941708,2.2956951
7,Lille,297939921,50.6365654,3.0635282
8,Strasbourg,297970735,48.584614,7.7507127
9,Chateau du Haut Koenigsbourg,120722565,48.249489800000006,7.34429620253195
10,Colmar,297941135,48.0777517,7.3579641
11,Eguisheim,297958707,48.0447968,7.3079618
12,Besancon,297963471,47.2380222,6.0243622
13,Dijon,297949589,47.3215806,5.0414701
14,Annecy,298996776,45.8992348,6.1288847
15,Grenoble,297959613,45.1875602,5.7357819
16,Lyon,298358151,45.7578137,4.8320114
17,Gorges du Verdon,76057079,43.7496562,6.3285616
18,Bormes les Mimosas,298218593,43.1506968,6.3419285
19,Cassis,297951775,43.2140359,5.5396318
20,Marseille,298048987,43.2961743,5.3699525
21,Aix en Provence,298018423,43.5298424,5.4474738
22,Avignon,297965181,43.9492493,4.8059012
23,Uzes,298413899,44.0121279,4.4196718
24,Nimes,298643421,43.8374249,4.3600687
25,Aigues Mortes,298067298,43.5658225,4.1912837
26,Saintes Maries de la mer,298133731,43.4522771,4.4287172
27,Collioure,297903903,42.52505,3.0831554
28,Carcassonne,297995754,43.2130358,2.3491069
29,Ariege,297848979,42.9455368,1.4065544156065486
30,Toulouse,297913876,43.6044622,1.4442469
31,Montauban,298355626,44.0175835,1.3549991
32,Biarritz,298725621,43.471143749999996,-1.552726590666314
33,Bayonne,298019575,43.4945144,-1.4736657
34,La Rochelle,297987288,46.1591126,-1.1520434

## 2 Récuperer les données via OpenWeather avec les règles de beau temps choisies

In [ ]:
df3 = pd.DataFrame()

for lati, longi in zip(df2['lat'], df2['lon']):

  r = requests.get("https://api.openweathermap.org/data/2.5/weather?lat=" + lati + "&lon=" + longi + "&exclude=current,minutely,hourly,alerts&appid=345eea7a2e2fba046096f8104b5e3506&units=metric")
  df3 = df3.append(r.json(), ignore_index=True)

<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)
<ipython-input-39-020e4aec5cb1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df3.append(r.json(), ignore_index=True)

In [ ]:
df3.head()

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod,rain
0,"{'lon': -1.5115, 'lat': 48.636}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 15.39, 'feels_like': 15.07, 'temp_min...",10000,"{'speed': 6.86, 'deg': 44, 'gust': 12.14}",{'all': 25},1685474548,"{'type': 1, 'id': 6557, 'country': 'FR', 'sunr...",7200,6435453,Huisnes-sur-Mer,200,NaN
1,"{'lon': -2.026, 'lat': 48.6495}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 15.59, 'feels_like': 15.08, 'temp_min...",10000,"{'speed': 6.69, 'deg': 50}",{'all': 0},1685474548,"{'type': 1, 'id': 6557, 'country': 'FR', 'sunr...",7200,2978640,St-Malo,200,NaN
2,"{'lon': -0.7025, 'lat': 49.2765}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 13.14, 'feels_like': 12.83, 'temp_min...",10000,"{'speed': 9.7, 'deg': 48, 'gust': 15.16}",{'all': 6},1685475107,"{'type': 1, 'id': 6569, 'country': 'FR', 'sunr...",7200,3034483,Bayeux,200,NaN
3,"{'lon': 0.108, 'lat': 49.4939}","[{'id': 803, 'main': 'Clouds', 'description': ...",stations,"{'temp': 13.51, 'feels_like': 13.06, 'temp_min...",10000,"{'speed': 8.75, 'deg': 40}",{'all': 75},1685475107,"{'type': 1, 'id': 6533, 'country': 'FR', 'sunr...",7200,3003796,Le Havre,200,NaN
4,"{'lon': 1.094, 'lat': 49.4405}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 17.11, 'feels_like': 16.57, 'temp_min...",10000,"{'speed': 6.17, 'deg': 20}",{'all': 0},1685475107,"{'type': 2, 'id': 2003589, 'country': 'FR', 's...",7200,2982652,Rouen,200,NaN

In [ ]:
df3['main'][0]['temp']

15.39

In [ ]:
a = [df3['main'][i]['temp'] for i in range(len(df3))]
print(a)

[15.39, 15.59, 13.14, 13.51, 17.11, 19.92, 13.43, 14.91, 21.77, 18.9, 21.94, 21.9, 19.13, 20.8, 21.73, 22.08, 24.22, 17.07, 22, 22.52, 22.52, 20.16, 22.75, 22.73, 23.21, 23.83, 23.69, 20.58, 19.2, 10.9, 25.97, 22.8, 19.09, 19.44, 24.07]

TypeError: ignored

In [ ]:
temps , prob , weather = [] , [] , []
    for j in range(len(response['daily'])):
        weather.append(response['daily'][j]['weather'][0]['main']) # Main meteo
        prob.append(response['daily'][j]['pop'] * 10) # Probality of precipitation
        temps.append(response['daily'][j]['feels_like']['day']) # Global temperature of the day